using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sentry.Godot.SourceGenerators;

[Generator]
public sealed class SentrySdkDelegationGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Methods to skip — these have custom implementations in the hand-written partial class.
    /// </summary>
    private static readonly HashSet<string> SkipMethods = new()
    {
        "Init",
    };

    /// <summary>
    /// Types whose members should be recursively generated as nested classes.
    /// Maps upstream type name to the wrapper class name.
    /// </summary>
    private static readonly Dictionary<string, string> NestedWrapperTypes = new()
    {
        { "ExperimentalSentrySdk", "ExperimentalSentrySdk" },
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        // Find the upstream Sentry.SentrySdk type.
        var upstreamSdk = compilation.GetTypeByMetadataName("Sentry.SentrySdk");
        if (upstreamSdk is null)
        {
            return;
        }

        // Find our Sentry.Godot.SentrySdk type to confirm it exists.
        var godotSdk = compilation.GetTypeByMetadataName("Sentry.Godot.SentrySdk");
        if (godotSdk is null)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Sentry.Infrastructure;");
        sb.AppendLine("using Sentry.Protocol.Envelopes;");
        sb.AppendLine();
        sb.AppendLine("namespace Sentry.Godot;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SentrySdk");
        sb.AppendLine("{");

        GenerateMembers(sb, upstreamSdk, "    ");

        sb.AppendLine("}");

        context.AddSource("SentrySdk.Dotnet.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateMembers(
        StringBuilder sb, INamedTypeSymbol sourceType, string indent)
    {
        var members = sourceType.GetMembers()
            .Where(m => m.DeclaredAccessibility == Accessibility.Public && m.IsStatic)
            .OrderBy(m => m.Kind)
            .ThenBy(m => m.Name);

        foreach (var member in members)
        {
            if (SkipMethods.Contains(member.Name))
            {
                continue;
            }

            switch (member)
            {
                case IPropertySymbol property:
                    GenerateProperty(sb, property, indent);
                    break;
                case IMethodSymbol method when method.MethodKind == MethodKind.Ordinary:
                    GenerateMethod(sb, method, indent);
                    break;
            }
        }

        // Generate nested wrapper types (e.g. ExperimentalSentrySdk).
        foreach (var nested in NestedWrapperTypes)
        {
            var nestedType = sourceType.GetTypeMembers(nested.Key)
                .FirstOrDefault(t => t.DeclaredAccessibility == Accessibility.Public);
            if (nestedType is null)
            {
                continue;
            }

            sb.AppendLine();
            AppendXmlDoc(sb, nestedType, indent);
            sb.AppendLine($"{indent}public sealed class {nested.Value}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    internal {nested.Value}()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}    }}");

            var nestedMembers = nestedType.GetMembers()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic)
                .OrderBy(m => m.Name);

            foreach (var nestedMember in nestedMembers)
            {
                if (nestedMember is IPropertySymbol nestedProp)
                {
                    sb.AppendLine();
                    AppendXmlDoc(sb, nestedProp, $"{indent}    ");
                    var returnType = FormatType(nestedProp.Type);
                    sb.AppendLine($"{indent}    public {returnType} {nestedProp.Name}");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        [DebuggerStepThrough]");
                    sb.AppendLine($"{indent}        get => Sentry.SentrySdk.Experimental.{nestedProp.Name};");
                    sb.AppendLine($"{indent}    }}");
                }
            }

            sb.AppendLine($"{indent}}}");
        }
    }

    private static void GenerateProperty(
        StringBuilder sb, IPropertySymbol property, string indent)
    {
        // Properties whose type is a nested wrapper get a static instance of our wrapper type.
        if (NestedWrapperTypes.ContainsKey(property.Type.Name))
        {
            sb.AppendLine();
            AppendXmlDoc(sb, property, indent);
            sb.AppendLine($"{indent}public static {property.Type.Name} Experimental {{ get; }} = new();");
            return;
        }

        var returnType = FormatType(property.Type);
        var qualifier = $"Sentry.SentrySdk.{property.Name}";

        sb.AppendLine();
        AppendXmlDoc(sb, property, indent);

        if (property.IsReadOnly)
        {
            sb.AppendLine($"{indent}public static {returnType} {property.Name} {{ [DebuggerStepThrough] get => {qualifier}; }}");
        }
        else
        {
            sb.AppendLine($"{indent}public static {returnType} {property.Name}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    [DebuggerStepThrough] get => {qualifier};");
            sb.AppendLine($"{indent}    [DebuggerStepThrough] set => {qualifier} = value;");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void GenerateMethod(
        StringBuilder sb, IMethodSymbol method, string indent)
    {
        var returnType = FormatType(method.ReturnType);

        // Build type parameters.
        var typeParams = "";
        var typeConstraints = new List<string>();
        if (method.IsGenericMethod)
        {
            typeParams = "<" + string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) + ">";
            foreach (var tp in method.TypeParameters)
            {
                var constraints = GetTypeParameterConstraints(tp);
                if (constraints.Length > 0)
                {
                    typeConstraints.Add($"where {tp.Name} : {constraints}");
                }
            }
        }

        // Build parameter list.
        var parameters = new List<string>();
        var arguments = new List<string>();
        foreach (var param in method.Parameters)
        {
            var paramType = FormatType(param.Type);
            var paramStr = $"{paramType} {param.Name}";

            if (param.RefKind == RefKind.Out)
            {
                paramStr = $"out {paramStr}";
                arguments.Add($"out {param.Name}");
            }
            else if (param.RefKind == RefKind.Ref)
            {
                paramStr = $"ref {paramStr}";
                arguments.Add($"ref {param.Name}");
            }
            else
            {
                arguments.Add(param.Name);
            }

            if (param.HasExplicitDefaultValue)
            {
                paramStr += $" = {FormatDefaultValue(param)}";
            }

            parameters.Add(paramStr);
        }

        var paramList = string.Join(", ", parameters);
        var argList = string.Join(", ", arguments);
        var constraintStr = typeConstraints.Count > 0
            ? " " + string.Join(" ", typeConstraints)
            : "";

        var attrs = GetMethodAttributes(method);

        sb.AppendLine();
        AppendXmlDoc(sb, method, indent);
        foreach (var attr in attrs)
        {
            sb.AppendLine($"{indent}{attr}");
        }
        sb.AppendLine($"{indent}[DebuggerStepThrough]");

        var call = $"Sentry.SentrySdk.{method.Name}{typeParams}({argList})";
        sb.AppendLine($"{indent}public static {returnType} {method.Name}{typeParams}({paramList}){constraintStr}");
        sb.AppendLine($"{indent}    => {call};");
    }

    private static string FormatType(ITypeSymbol type)
    {
        var format = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        return type.ToDisplayString(format);
    }

    private static string FormatDefaultValue(IParameterSymbol param)
    {
        if (!param.HasExplicitDefaultValue)
        {
            return "";
        }

        var value = param.ExplicitDefaultValue;

        if (value is null)
        {
            return "null";
        }

        if (param.Type.TypeKind == TypeKind.Enum)
        {
            var enumType = param.Type;
            foreach (var member in enumType.GetMembers())
            {
                if (member is IFieldSymbol field && field.HasConstantValue &&
                    field.ConstantValue?.Equals(value) == true)
                {
                    return $"{FormatType(enumType)}.{field.Name}";
                }
            }
            return $"({FormatType(enumType)}){value}";
        }

        if (value is string s)
        {
            return $"\"{s}\"";
        }

        if (value is bool b)
        {
            return b ? "true" : "false";
        }

        return value.ToString()!;
    }

    private static string GetTypeParameterConstraints(ITypeParameterSymbol tp)
    {
        var parts = new List<string>();

        if (tp.HasReferenceTypeConstraint)
        {
            parts.Add("class");
        }
        if (tp.HasValueTypeConstraint)
        {
            parts.Add("struct");
        }
        foreach (var constraint in tp.ConstraintTypes)
        {
            parts.Add(FormatType(constraint));
        }
        if (tp.HasConstructorConstraint)
        {
            parts.Add("new()");
        }

        return string.Join(", ", parts);
    }

    private static List<string> GetMethodAttributes(IMethodSymbol method)
    {
        var attrs = new List<string>();

        foreach (var attr in method.GetAttributes())
        {
            var name = attr.AttributeClass?.ToDisplayString();
            if (name == "System.ComponentModel.EditorBrowsableAttribute")
            {
                attrs.Add("[EditorBrowsable(EditorBrowsableState.Never)]");
            }
            else if (name == "System.ObsoleteAttribute")
            {
                var msg = attr.ConstructorArguments.Length > 0
                    ? $"(\"{attr.ConstructorArguments[0].Value}\")"
                    : "";
                attrs.Add($"[Obsolete{msg}]");
            }
        }

        return attrs;
    }

    private static void AppendXmlDoc(StringBuilder sb, ISymbol symbol, string indent)
    {
        var xml = symbol.GetDocumentationCommentXml();
        if (string.IsNullOrWhiteSpace(xml))
        {
            return;
        }

        // The raw XML is wrapped in <member name="...">...</member>.
        // Extract the inner content.
        var lines = xml!.Split('\n');
        foreach (var rawLine in lines)
        {
            var line = rawLine.TrimEnd('\r');
            if (line.TrimStart().StartsWith("<member") || line.TrimStart().StartsWith("</member"))
            {
                continue;
            }
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }
            sb.AppendLine($"{indent}/// {line.TrimStart()}");
        }
    }
}
