using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Sentry.Godot.SourceGenerators;

[Generator]
public sealed class SentrySdkDelegationGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Methods to skip — these have custom implementations in the hand-written partial class.
    /// </summary>
    private static readonly HashSet<string> SkipMethods =
    [
        "Init",
        "Close"
    ];

    private const string DiagnosticCategory = "Sentry.Godot.SourceGenerators";

    private static readonly DiagnosticDescriptor UpstreamSdkNotFound = new(
        id: "SGSDK001",
        title: "Upstream Sentry SDK type not found",
        messageFormat: "'Sentry.SentrySdk' could not be resolved — ensure the 'Sentry' NuGet package is referenced",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor GodotSdkNotFound = new(
        id: "SGSDK002",
        title: "Sentry.Godot SDK partial class not found",
        messageFormat: "'Sentry.Godot.SentrySdk' could not be resolved — the hand-written partial class required by the generator is missing",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, Execute);
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        // Find the upstream Sentry.SentrySdk type.
        var upstreamSdk = compilation.GetTypeByMetadataName("Sentry.SentrySdk");
        if (upstreamSdk is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(UpstreamSdkNotFound, Location.None));
            return;
        }

        // Find our Sentry.Godot.SentrySdk type to confirm it exists.
        var godotSdk = compilation.GetTypeByMetadataName("Sentry.Godot.SentrySdk");
        if (godotSdk is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(GodotSdkNotFound, Location.None));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine();
        sb.AppendLine("namespace Sentry.Godot;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SentrySdk");
        sb.AppendLine("{");

        GenerateMembers(sb, upstreamSdk, "    ");

        sb.AppendLine("}");

        context.AddSource("SentrySdk.Dotnet.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateMembers(
        StringBuilder sb, INamedTypeSymbol sourceType, string indent)
    {
        var members = sourceType.GetMembers()
            .Where(m => m.DeclaredAccessibility == Accessibility.Public && m.IsStatic)
            .OrderBy(m => m.Kind)
            .ThenBy(m => m.Name);

        foreach (var member in members)
        {
            if (SkipMethods.Contains(member.Name))
            {
                continue;
            }

            switch (member)
            {
                case IPropertySymbol property:
                    GenerateProperty(sb, property, indent, "static ", "global::Sentry.SentrySdk", isTopLevel: true);
                    break;
                case IMethodSymbol method when method.MethodKind == MethodKind.Ordinary:
                    GenerateMethod(sb, method, indent, "static ", "global::Sentry.SentrySdk");
                    break;
            }
        }

        // Generate wrapper classes for every public nested type exposed via a public
        // static property. This auto-discovers upstream hubs like ExperimentalSentrySdk.
        foreach (var nestedType in sourceType.GetTypeMembers()
            .Where(t => t.DeclaredAccessibility == Accessibility.Public)
            .OrderBy(t => t.Name))
        {
            var outerProperty = sourceType.GetMembers()
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.IsStatic
                    && p.DeclaredAccessibility == Accessibility.Public
                    && SymbolEqualityComparer.Default.Equals(p.Type, nestedType));
            if (outerProperty is null)
            {
                continue;
            }

            var qualifier = $"global::Sentry.SentrySdk.{outerProperty.Name}";

            sb.AppendLine();
            AppendInheritDoc(sb, nestedType, indent);
            sb.AppendLine($"{indent}public sealed class {nestedType.Name}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    internal {nestedType.Name}()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}    }}");

            var nestedMembers = nestedType.GetMembers()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic)
                .OrderBy(m => m.Kind)
                .ThenBy(m => m.Name);

            foreach (var nestedMember in nestedMembers)
            {
                switch (nestedMember)
                {
                    case IPropertySymbol nestedProp:
                        GenerateProperty(sb, nestedProp, $"{indent}    ", "", qualifier, isTopLevel: false);
                        break;
                    case IMethodSymbol nestedMethod when nestedMethod.MethodKind == MethodKind.Ordinary:
                        GenerateMethod(sb, nestedMethod, $"{indent}    ", "", qualifier);
                        break;
                }
            }

            sb.AppendLine($"{indent}}}");
        }
    }

    private static void GenerateProperty(
        StringBuilder sb, IPropertySymbol property, string indent,
        string staticModifier, string qualifier, bool isTopLevel)
    {
        sb.AppendLine();
        AppendInheritDoc(sb, property, indent);
        foreach (var attr in GetForwardedAttributes(property))
        {
            sb.AppendLine($"{indent}{attr}");
        }

        // Top-level properties whose type is a public nested type of the upstream SDK
        // get a static instance of our auto-discovered wrapper type.
        if (isTopLevel
            && property.Type is INamedTypeSymbol nestedType
            && nestedType.DeclaredAccessibility == Accessibility.Public
            && SymbolEqualityComparer.Default.Equals(nestedType.ContainingType, property.ContainingType))
        {
            sb.AppendLine($"{indent}public {staticModifier}{nestedType.Name} {property.Name} {{ get; }} = new();");
            return;
        }

        var returnType = FormatType(property.Type);
        var accessor = $"{qualifier}.{property.Name}";

        if (property.IsReadOnly)
        {
            sb.AppendLine($"{indent}public {staticModifier}{returnType} {property.Name} {{ [DebuggerStepThrough] get => {accessor}; }}");
        }
        else
        {
            sb.AppendLine($"{indent}public {staticModifier}{returnType} {property.Name}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    [DebuggerStepThrough] get => {accessor};");
            sb.AppendLine($"{indent}    [DebuggerStepThrough] set => {accessor} = value;");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void GenerateMethod(
        StringBuilder sb, IMethodSymbol method, string indent,
        string staticModifier, string qualifier)
    {
        var returnType = FormatType(method.ReturnType);

        // Build type parameters.
        var typeParams = "";
        var typeConstraints = new List<string>();
        if (method.IsGenericMethod)
        {
            typeParams = "<" + string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) + ">";
            foreach (var tp in method.TypeParameters)
            {
                var constraints = GetTypeParameterConstraints(tp);
                if (constraints.Length > 0)
                {
                    typeConstraints.Add($"where {tp.Name} : {constraints}");
                }
            }
        }

        // Build parameter list.
        var parameters = new List<string>();
        var arguments = new List<string>();
        foreach (var param in method.Parameters)
        {
            var paramType = FormatType(param.Type);
            var paramStr = $"{paramType} {param.Name}";

            if (param.RefKind == RefKind.Out)
            {
                paramStr = $"out {paramStr}";
                arguments.Add($"out {param.Name}");
            }
            else if (param.RefKind == RefKind.Ref)
            {
                paramStr = $"ref {paramStr}";
                arguments.Add($"ref {param.Name}");
            }
            else if (param.IsParams)
            {
                paramStr = $"params {paramStr}";
                arguments.Add(param.Name);
            }
            else
            {
                arguments.Add(param.Name);
            }

            if (param.HasExplicitDefaultValue)
            {
                paramStr += $" = {FormatConstantValue(param.Type, param.ExplicitDefaultValue)}";
            }

            parameters.Add(paramStr);
        }

        var paramList = string.Join(", ", parameters);
        var argList = string.Join(", ", arguments);
        var constraintStr = typeConstraints.Count > 0
            ? " " + string.Join(" ", typeConstraints)
            : "";

        var attrs = GetForwardedAttributes(method);

        sb.AppendLine();
        AppendInheritDoc(sb, method, indent);
        foreach (var attr in attrs)
        {
            sb.AppendLine($"{indent}{attr}");
        }
        sb.AppendLine($"{indent}[DebuggerStepThrough]");

        var call = $"{qualifier}.{method.Name}{typeParams}({argList})";
        sb.AppendLine($"{indent}public {staticModifier}{returnType} {method.Name}{typeParams}({paramList}){constraintStr}");
        sb.AppendLine($"{indent}    => {call};");
    }

    private static string FormatType(ITypeSymbol type)
    {
        var format = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        return type.ToDisplayString(format);
    }

    private static string FormatConstantValue(ITypeSymbol? type, object? value)
    {
        if (value is null)
        {
            // Non-nullable value-type parameters with `= default` report a null
            // ExplicitDefaultValue. Emitting "null" would be a compile error;
            // emit `default(T)` instead. Nullable<T> is excluded so `int? x = null`
            // still emits as "null".
            if (type is { IsValueType: true }
                && type.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T)
            {
                return $"default({FormatType(type)})";
            }
            return "null";
        }

        if (type is { TypeKind: TypeKind.Enum })
        {
            foreach (var member in type.GetMembers())
            {
                if (member is IFieldSymbol field && field.HasConstantValue &&
                    field.ConstantValue?.Equals(value) == true)
                {
                    return $"{FormatType(type)}.{field.Name}";
                }
            }
            return $"({FormatType(type)}){FormatPrimitiveLiteral(value)}";
        }

        if (value is string s)
        {
            return SymbolDisplay.FormatLiteral(s, quote: true);
        }

        if (value is bool b)
        {
            return b ? "true" : "false";
        }

        if (value is char c)
        {
            return SymbolDisplay.FormatLiteral(c, quote: true);
        }

        return FormatPrimitiveLiteral(value);
    }

    private static string FormatTypedConstant(TypedConstant tc)
    {
        if (tc.IsNull)
        {
            return "null";
        }

        if (tc.Kind == TypedConstantKind.Array)
        {
            var items = tc.Values.Select(FormatTypedConstant);
            return $"new[] {{ {string.Join(", ", items)} }}";
        }

        if (tc.Kind == TypedConstantKind.Type && tc.Value is ITypeSymbol typeValue)
        {
            return $"typeof({FormatType(typeValue)})";
        }

        return FormatConstantValue(tc.Type, tc.Value);
    }

    private static string FormatPrimitiveLiteral(object value)
    {
        var inv = CultureInfo.InvariantCulture;
        return value switch
        {
            float f => f.ToString("R", inv) + "F",
            double d => d.ToString("R", inv) + "D",
            decimal m => m.ToString(inv) + "M",
            long l => l.ToString(inv) + "L",
            ulong ul => ul.ToString(inv) + "UL",
            uint u => u.ToString(inv) + "U",
            IFormattable fmt => fmt.ToString(null, inv),
            _ => value.ToString()!,
        };
    }

    private static string GetTypeParameterConstraints(ITypeParameterSymbol tp)
    {
        var parts = new List<string>();

        if (tp.HasReferenceTypeConstraint)
        {
            parts.Add("class");
        }
        if (tp.HasValueTypeConstraint)
        {
            parts.Add("struct");
        }
        foreach (var constraint in tp.ConstraintTypes)
        {
            parts.Add(FormatType(constraint));
        }
        if (tp.HasConstructorConstraint)
        {
            parts.Add("new()");
        }

        return string.Join(", ", parts);
    }

    /// <summary>
    /// Attributes that must not be forwarded to the generated wrapper — either
    /// compiler-synthesized or already emitted unconditionally by the generator itself.
    /// </summary>
    private static readonly HashSet<string> SkipAttributes =
    [
        "System.Diagnostics.DebuggerStepThroughAttribute",
        "System.Runtime.CompilerServices.NullableContextAttribute",
        "System.Runtime.CompilerServices.NullableAttribute",
        "System.Runtime.CompilerServices.AsyncStateMachineAttribute",
        "System.Runtime.CompilerServices.IteratorStateMachineAttribute",
        "System.Runtime.CompilerServices.CompilerGeneratedAttribute",
    ];

    private static List<string> GetForwardedAttributes(ISymbol symbol)
    {
        var attrs = new List<string>();
        foreach (var attr in symbol.GetAttributes())
        {
            var name = attr.AttributeClass?.ToDisplayString();
            if (name is null || SkipAttributes.Contains(name))
            {
                continue;
            }
            attrs.Add(FormatAttribute(attr));
        }
        return attrs;
    }

    private static string FormatAttribute(AttributeData attr)
    {
        var typeName = FormatType(attr.AttributeClass!);
        if (typeName.EndsWith("Attribute"))
        {
            typeName = typeName.Substring(0, typeName.Length - "Attribute".Length);
        }

        var args = new List<string>();
        foreach (var arg in attr.ConstructorArguments)
        {
            args.Add(FormatTypedConstant(arg));
        }
        foreach (var named in attr.NamedArguments)
        {
            args.Add($"{named.Key} = {FormatTypedConstant(named.Value)}");
        }

        return args.Count > 0
            ? $"[{typeName}({string.Join(", ", args)})]"
            : $"[{typeName}]";
    }

    // We can't emit the upstream doc text literally: GetDocumentationCommentXml()
    // returns empty for types loaded via a metadata reference. But the doc-comment
    // ID is always available, so cref-based inheritance lets any Roslyn-aware
    // tooling resolve the target's docs from the referenced package's .xml file.
    private static void AppendInheritDoc(StringBuilder sb, ISymbol symbol, string indent)
    {
        var docId = symbol.GetDocumentationCommentId();
        if (docId is null)
        {
            return;
        }
        sb.AppendLine($"{indent}/// <inheritdoc cref=\"{docId}\"/>");
    }
}
