changelogPolicy: auto
preReleaseCommand: pwsh scripts/bump-version.ps1
postReleaseCommand: pwsh scripts/post-release.ps1
targets:
  - name: github
  - name: registry
    sdks:
      github:getsentry/sentry-godot:
