name: Prepare testing
description: Set up environment for testing purposes.

inputs:
  arch:
    description: Architecture to use for testing.
    required: true
  export-platform:
    description: Which export template will be used, lowercase (e.g., android, ios).
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout required submodules
      shell: bash
      run: |
        git submodule update --init --depth 1 modules/app-runner
        git submodule update --init --depth 1 modules/gdUnit4
        git submodule update --init --depth 1 modules/godot-cpp
        git submodule update --init --depth 1 project/test/util/json_assert

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: sentry-godot-gdextension
        path: project/

    - name: Install SCons
      shell: bash
      run: |
        python -m pip install scons
        python --version
        scons --version

    - name: Set up Java 17
      if: inputs.export-platform == 'android'
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: temurin
        java-version: 17

    - name: Install Linux dependencies (32-bit)
      if: runner.os == 'Linux' && inputs.arch == 'x86_32'
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install \
            libatomic1:i386 \
            libudev1:i386 \
            libfontconfig1:i386 \
            libcurl4-openssl-dev:i386 \
            zlib1g:i386

    - name: Set up Godot
      shell: bash
      env:
        # Set Godot version override here (e.g. "4.5.1-stable").
        GODOT_VERSION_OVERRIDE: 4.5.1-stable
        ARCH: ${{ inputs.arch }}
      run: |
        if [[ -n "$GODOT_VERSION_OVERRIDE" ]]; then
          version="$GODOT_VERSION_OVERRIDE"
        else
          major_minor=$(sed -n 's/compatibility_minimum = "\([^"]*\)"/\1/p' project/addons/sentry/sentry.gdextension)
          version="${major_minor}-stable"
        fi

        echo "Using Godot version: $version"
        echo "GODOT_VERSION=$version" >> $GITHUB_ENV

        if [[ "$RUNNER_OS" == "Windows" ]]; then
          if [[ "$ARCH" == "x86_32" ]]; then
            suffix=win32.exe
          elif [[ "$ARCH" == "x86_64" ]]; then
            suffix=win64.exe
          elif [[ "$ARCH" == "arm64" ]]; then
            suffix=windows_arm64.exe
          else
            echo "Unexpected Windows architecture: $ARCH"
            exit 1
          fi
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          if [[ "$ARCH" == "x86_32" ]]; then
            suffix=linux.x86_32
          elif [[ "$ARCH" == "x86_64" ]]; then
            suffix=linux.x86_64
          elif [[ "$ARCH" == "arm64" ]]; then
            suffix=linux_arm64
          else
            echo "Unexpected Linux architecture: $ARCH"
            exit 1
          fi
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          if [[ "$ARCH" == "universal" ]]; then
            suffix=macos.universal
          else
            echo "Unexpected macOS architecture: $ARCH"
            exit 1
          fi
        fi

        archive_file=Godot_v${version}_${suffix}.zip
        url=https://github.com/godotengine/godot-builds/releases/download/${version}/${archive_file}
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          bin=${GITHUB_WORKSPACE}/godot/Godot.app/Contents/MacOS/Godot
        else
          bin=${GITHUB_WORKSPACE}/godot/Godot_v${version}_${suffix}
        fi
        mkdir godot/
        cd godot/
        echo "Downloading ${url}"
        curl -L -o godot.zip "${url}"
        unzip godot.zip
        rm godot.zip
        chmod u+x ${bin}
        ls -l
        ${bin} --version
        echo "GODOT=${bin}" >> $GITHUB_ENV

    - name: Diagnostic info
      shell: bash
      run: |
        ls -lR project/

    - name: Fetch kaboom addon
      shell: bash
      run: scons kaboom

    - name: Prepare gdUnit4
      shell: bash
      run: |
        scons project/addons/gdUnit4

    - name: Prepare export configuration
      shell: bash
      run: cp exports/export_presets.cfg project/export_presets.cfg

    - name: Download export templates
      if: inputs.export-platform != ''
      shell: bash
      run: |
        # Download Godot templates
        archive_file=Godot_v${GODOT_VERSION}_export_templates.tpz
        url=https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/${archive_file}
        echo "Downloading templates from: $url"
        curl -L -o templates.zip "${url}"

        echo "Extracting export templates..."
        mkdir -p exports/templates
        unzip -j templates.zip -d exports/templates
        rm templates.zip

    - name: Prepare project
      shell: bash
      run: |
        find project/addons/sentry/bin/ -name "crashpad_handler" -exec chmod 755 "{}" \;
        echo "--- Rebuilding import cache"
        ${GODOT} --headless --path project/ --import --verbose
        echo "--- Finished rebuilding import cache"
