name: Prepare testing
description: Set up environment for testing purposes.

runs:
  using: "composite"
  steps:
    - name: Checkout required submodules
      shell: bash
      run: |
        git submodule update --init --depth 1 modules/gdUnit4
        git submodule update --init --depth 1 modules/godot-cpp

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: sentry-godot-gdextension
        path: project/

    - name: Install SCons
      shell: bash
      run: |
        python -m pip install scons
        python --version
        scons --version

    - name: Set up Godot
      env:
        # Set pre-release version status here (e.g. "beta1");
        # for release version, set to "stable".
        release_status: "beta1"
      shell: bash
      run: |
        major_minor=$(sed -n 's/compatibility_minimum = "\([^"]*\)"/\1/p' project/addons/sentry/bin/sentry.gdextension)
        version=${major_minor}-${release_status}
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          suffix=win64.exe
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          suffix=linux.x86_64
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          suffix=macos.universal
        fi
        archive_file=Godot_v${version}_${suffix}.zip
        url=https://github.com/godotengine/godot-builds/releases/download/${version}/${archive_file}
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          bin=${GITHUB_WORKSPACE}/godot/Godot.app/Contents/MacOS/Godot
        else
          bin=${GITHUB_WORKSPACE}/godot/Godot_v${version}_${suffix}
        fi
        mkdir godot/
        cd godot/
        echo "Downloading ${url}"
        curl -L -o godot.zip "${url}"
        unzip godot.zip
        rm godot.zip
        chmod u+x ${bin}
        ls -l
        ${bin} --version
        echo "GODOT=${bin}" >> $GITHUB_ENV

    - name: Diagnostic info
      shell: bash
      run: |
        ls -lR project/

    - name: Prepare gdUnit4
      shell: bash
      run: |
        scons project/addons/gdUnit4
        echo "Applying gdUnit4 patch"
        cd modules/gdUnit4
        # NOTE: Patching gdUnit4 as it errors out in Godot 4.5.
        git apply ../gdunit4.patch

    - name: Prepare project
      shell: bash
      # timeout-minutes: 5
      run: |
        chmod +x project/addons/sentry/bin/{linux,macos}/crashpad_handler
        echo "--- Rebuilding import cache"
        ${GODOT} --headless --editor --path project/ --quit-after 2000 || true
        echo "--- Finished rebuilding import cache"
