name: ⚙️ CI

on:
  push:
    branches:
      - "main"
      - "release/**"
    paths-ignore:
      - "*.md"

  pull_request:

# Cancel in-progress runs on PR update and on push.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-extension:
    name: 🔌 Build GDExtension
    uses: ./.github/workflows/build_gdextension.yml

  static-checks:
    name: 🔎 Static checks
    needs: build-extension
    uses: ./.github/workflows/static_checks.yml

  unit-tests:
    name: 🧪 Unit tests
    needs: build-extension
    uses: ./.github/workflows/unit_tests.yml

  test-android:
    name: 🧪 Android tests
    needs: build-extension
    uses: ./.github/workflows/test_android.yml

  test-web:
    name: 🧪 Web tests
    needs: build-extension
    uses: ./.github/workflows/test_web.yml

  test-integration:
    name: 🧪 Integration tests
    needs: build-extension
    uses: ./.github/workflows/test_integration.yml
    secrets:
      SENTRY_API_TOKEN: ${{ secrets.SENTRY_API_TOKEN }}
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
      MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  test-js-bridge:
    name: 🧪 JS bridge tests
    uses: ./.github/workflows/test_js_bridge.yml

  package:
    name: 📦 Package
    needs: build-extension
    uses: ./.github/workflows/package.yml
    secrets:
      APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}

  # Deleting "sentry-godot-gdextension" artifact due to broken file permissions.
  # This encourages using the artifact from the "package" job instead which has correct permissions.
  # See issue: https://github.com/getsentry/sentry-godot/issues/41
  cleanup:
    name: 🗑️ Cleanup
    needs: [package, unit-tests, test-android, test-web, test-integration, static-checks, test-js-bridge]
    runs-on: ubuntu-latest
    steps:
      - name: Delete sentry-godot-gdextension artifact
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          name: sentry-godot-gdextension
