name: ✍️ Sign macOS builds

on:
  workflow_call:

jobs:
  sing-macos-builds:
    runs-on: ubuntu-latest

    env:
      CODESIGN_VERSION: 0.29.0
      APPLE_CERT_PATH: /tmp/certs.p12
      APPLE_API_KEY_PATH: /tmp/apple_key.json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install `rcodesign`
        run: |
          curl -L https://github.com/indygreg/apple-platform-rs/releases/download/apple-codesign/${CODESIGN_VERSION}/apple-codesign-${CODESIGN_VERSION}-x86_64-unknown-linux-musl.tar.gz \
            -o rcodesign.tar.gz
          echo "dbe85cedd8ee4217b64e9a0e4c2aef92ab8bcaaa41f20bde99781ff02e600002  rcodesign.tar.gz" | sha256sum -c -
          tar -xz --strip-components=1 -f rcodesign.tar.gz
          mv rcodesign /usr/local/bin/rcodesign
          rm rcodesign.tar.gz

      - name: Decode Apple signing certificate and API key
        env:
          APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
        run: |
          echo "$APPLE_CERT_DATA" | base64 --decode > ${{ env.APPLE_CERT_PATH }}
          echo "$APPLE_API_KEY" | base64 --decode > ${{ env.APPLE_API_KEY_PATH }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sentry-godot-gdextension
          path: artifact/

      - name: Sign binaries
        run: |
          rcodesign sign --for-notarization \
            --p12-file ${{ env.APPLE_CERT_PATH }} --p12-password ${{ secrets.APPLE_CERT_PASSWORD }} \
            artifact/addons/sentrysdk/bin/macos/libsentrysdk.macos.debug.framework/libsentrysdk.macos.debug
          rcodesign sign --for-notarization \
            --p12-file ${{ env.APPLE_CERT_PATH }} --p12-password ${{ secrets.APPLE_CERT_PASSWORD }} \
            artifact/addons/sentrysdk/bin/macos/libsentrysdk.macos.release.framework/libsentrysdk.macos.release
          rcodesign sign --for-notarization \
            --p12-file ${{ env.APPLE_CERT_PATH }} --p12-password ${{ secrets.APPLE_CERT_PASSWORD }} \
            artifact/addons/sentrysdk/bin/macos/crashpad_handler

          # --entitlements-xml-path entitlements.plist

      # - name: Notarize binaries
      #   run: |
      #     notarize_cmd=rcodesign notary-submit \
      #       --api-key-file ${{ env.APPLE_API_KEY_PATH }} \
      #       --wait

      #     ${notarize_cmd} artifact/addons/sentrysdk/bin/macos/libsentrysdk.macos.debug.framework/libsentrysdk.macos.debug
      #     ${notarize_cmd} artifact/addons/sentrysdk/bin/macos/libsentrysdk.macos.release.framework/libsentrysdk.macos.release
      #     ${notarize_cmd} artifact/addons/sentrysdk/bin/macos/crashpad_handler

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentry-godot-gdextension
          path: artifact/*
          overwrite: true
