name: 📦 Package

on:
  workflow_call:
    secrets:
      APPLE_CERT_DATA:
        required: false
      APPLE_CERT_PASSWORD:
        required: false
      APPLE_API_KEY:
        required: false

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest

    env:
      APPLE_CERT_PATH: /tmp/certs.p12
      APPLE_API_KEY_PATH: /tmp/apple_key.json
      DO_CODESIGN: ${{ startsWith(github.ref, 'refs/heads/release/') && '1' || '0' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Download artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: sentry-godot-gdextension
          path: project/

      - name: Decode Apple signing certificate and API key
        if: env.DO_CODESIGN == '1'
        env:
          APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
        run: |
          if [ -z "$APPLE_CERT_DATA" ] || [ -z "$APPLE_API_KEY" ]; then
            echo "::error title=Codesign failed::Missing Apple signing certificate or API key."
            exit 1
          fi
          echo "$APPLE_CERT_DATA" | base64 --decode > ${{ env.APPLE_CERT_PATH }}
          echo "$APPLE_API_KEY" | base64 --decode > ${{ env.APPLE_API_KEY_PATH }}

      - name: Install rcodesign
        if: env.DO_CODESIGN == '1'
        env:
          CODESIGN_VERSION: 0.29.0
          CODESIGN_CHECKSUM: dbe85cedd8ee4217b64e9a0e4c2aef92ab8bcaaa41f20bde99781ff02e600002
        run: |
          curl -L https://github.com/indygreg/apple-platform-rs/releases/download/apple-codesign/${CODESIGN_VERSION}/apple-codesign-${CODESIGN_VERSION}-x86_64-unknown-linux-musl.tar.gz \
            -o rcodesign.tar.gz
          echo "${CODESIGN_CHECKSUM}  rcodesign.tar.gz" | sha256sum -c -
          tar -xz --strip-components=1 -f rcodesign.tar.gz
          mv rcodesign /usr/local/bin/rcodesign
          rm rcodesign.tar.gz

      - name: Sign macOS binaries
        if: env.DO_CODESIGN == '1'
        run: |
          rcodesign sign --for-notarization \
            --p12-file ${{ env.APPLE_CERT_PATH }} --p12-password ${{ secrets.APPLE_CERT_PASSWORD }} \
            project/addons/sentry/bin/macos/libsentry.macos.debug.dylib
          rcodesign sign --for-notarization \
            --p12-file ${{ env.APPLE_CERT_PATH }} --p12-password ${{ secrets.APPLE_CERT_PASSWORD }} \
            project/addons/sentry/bin/macos/libsentry.macos.release.dylib
          rcodesign sign --for-notarization \
            --p12-file ${{ env.APPLE_CERT_PATH }} --p12-password ${{ secrets.APPLE_CERT_PASSWORD }} \
            project/addons/sentry/bin/macos/libSentry.dylib

      - name: Notarize macOS binaries
        if: env.DO_CODESIGN == '1'
        run: |
          cd project/addons/sentry/bin/macos/

          zip -r sentry-godot-dylibs.zip libsentry.macos.debug.dylib libsentry.macos.release.dylib libSentry.dylib
          rcodesign notary-submit --wait \
            --api-key-file ${{ env.APPLE_API_KEY_PATH }} \
            sentry-godot-dylibs.zip
          rm sentry-godot-dylibs.zip

      - name: Assemble packages
        run: scripts/package.sh --source project/ --output out/

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: ${{github.sha}}
          path: out/*
