name: 🧪 C++ tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  cpp-tests:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: false

      - name: Checkout required submodules
        shell: bash
        run: |
          git submodule update --init --recursive --depth 1 \
            modules/godot-cpp \
            modules/sentry-native \
            modules/gdUnit4 \
            modules/doctest

      - name: Install Linux build deps
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev

      - name: Install SCons
        run: python -m pip install scons

      - name: Build GDExtension with tests
        run: scons tests=yes target=editor

      - name: Set up .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: 8.0.x

      - name: Set up Godot
        run: ./scripts/setup-godot.sh --mono

      - name: Build .NET solution
        shell: bash
        env:
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        run: dotnet build Sentry.Godot.slnx

      - name: Run tests
        shell: bash
        timeout-minutes: 2
        run: |
          "${GODOT}" --headless --path project/ --editor --test-sentry
