name: 🧪 Unit tests

on:
  workflow_call:

jobs:
  unit-tests:
    name: Test ${{matrix.runner}} ${{matrix.arch}}
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            arch: x86_64
          - runner: windows-latest
            arch: x86_32
          - runner: ubuntu-latest
            arch: x86_64
          - runner: ubuntu-latest
            arch: x86_32
          - runner: macos-latest
            arch: universal
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false # don't initialize submodules automatically

      - name: Prepare testing
        uses: ./.github/actions/prepare-testing
        with:
          arch: ${{ matrix.arch }}

      - name: Run tests
        shell: bash
        timeout-minutes: 5
        run: |
          # Exit status codes: 0 - success, 100 - ends with test failures, 101 - ends with test warnings.
          ${GODOT} --headless --path project/ -s -d "res://addons/gdUnit4/bin/GdUnitCmdTool.gd" --ignoreHeadlessMode -c -a test/suites/

      - name: Run isolated tests
        if: success() || failure()
        shell: pwsh
        timeout-minutes: 5
        run: ./scripts/run-isolated-tests.ps1

      - name: Upload results
        if: always() # do this step even if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{matrix.runner}}-${{matrix.arch}}
          path: project/reports
