name: Update Dependencies

on:
  # Run every day.
  schedule:
    - cron: "0 3 * * *"
  # Allow a manual trigger to be able to run the update when there are new dependencies or after a PR merge to resolve CHANGELOG conflicts.
  workflow_dispatch:

permissions:
  contents: write # needed to add commits to branches
  pull-requests: write
  actions: write # needed for cancelling workflow runs

jobs:
  deps:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Native SDK
            path: modules/sentry-native
          - name: Cocoa SDK
            path: modules/sentry-cocoa.properties
          - name: gdUnit 4
            path: modules/gdUnit4
    uses: getsentry/github-workflows/.github/workflows/updater.yml@v2
    with:
      name: ${{ matrix.name }}
      path: ${{ matrix.path }}
      pr-strategy: update
    secrets:
      api-token: ${{ secrets.CI_DEPLOY_KEY }}

  android:
    name: Sentry Android
    uses: getsentry/github-workflows/.github/workflows/updater.yml@v2
    with:
      name: Sentry Android
      path: scripts/android-version.ps1
      pr-strategy: update
    secrets:
      api-token: ${{ secrets.CI_DEPLOY_KEY }}
